# **Sarcasm Detection System**
# **Abhishek 19BCI7058**

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import preprocessing
from tensorflow.keras import optimizers,losses
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing import text
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding,Flatten,SimpleRNN
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data=pd.read_csv("/content/drive/MyDrive/Sarcasm/train-balanced-sarcasm.csv")
data=pd.DataFrame(data)
X=data.iloc[:50000,1]
Y=data.iloc[:50000,0]
X=np.asarray(X)
Y=np.asarray(Y)
X=X.astype(str)
G=[one_hot(h,500) for h in X]
outputs=Y  
print(G)
print(outputs)

[[37, 312, 465], [125, 213, 29, 47, 280, 155, 128, 47, 280, 486, 13, 247, 280, 342], [331, 154, 158, 464, 176, 211, 47, 450, 259, 117, 333, 90, 347, 197, 99, 352, 144, 263, 202], [117, 33, 279, 366, 213, 24, 90, 453, 293, 441, 467, 140], [498, 163, 187, 182, 24, 384, 456], [498, 421, 104, 77, 144, 412, 211, 488, 149, 488, 469, 229, 498, 308, 376, 412, 220, 24, 333, 454, 82, 326, 101, 335], [163, 189, 160, 408, 79, 450, 443, 416], [475, 418, 378, 189, 422], [125, 421, 188, 144, 125, 188, 101, 111, 489, 67, 27, 189, 481, 72], [498, 451, 386, 144, 201, 164, 59, 21], [498, 180, 101, 214, 351, 451, 334, 128, 480, 303, 116, 313, 284, 493, 313], [344, 498, 330, 242, 288, 330, 441], [331, 188, 495, 208], [251, 479], [419, 248, 250, 72, 357, 101, 48, 486, 70, 408, 478], [86, 90, 53], [35], [75, 260, 86, 23, 375, 164, 312, 260, 101, 52, 24, 26], [108, 125, 97, 292, 329, 264], [197, 237, 34, 312, 253], [82, 57, 164, 280, 51, 420, 412, 166, 310, 90, 117, 484, 240, 340, 431, 312, 53], [59, 117, 270

In [ ]:
padded=pad_sequences(G,maxlen=40,padding='post')
print(padded)

[[ 37 312 465 ...   0   0   0]
 [125 213  29 ...   0   0   0]
 [331 154 158 ...   0   0   0]
 ...
 [383 163  80 ...   0   0   0]
 [114 456  25 ...   0   0   0]
 [458 101 275 ...   0   0   0]]


In [ ]:
model=Sequential()
model.add(Embedding(500,12,input_length=40,name='embed'))
model.add(SimpleRNN(30))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
padded=tensorflow.convert_to_tensor(padded)
testing="You do know west teams play against west teams more than east teams right?"
testing=one_hot(testing,500)
print(testing)
test=[]
for h in range(0,40):
  if h<len(testing):
   test.append(testing[h])
  else:
    test.append(0) 
test=[test]    
outputs=tensorflow.convert_to_tensor(outputs)
model.fit(padded,outputs,epochs=25)
q=model.predict(test,batch_size=3)
if q[0][0]>0.5:
  print("No sarcasm detected")
else:
  print("Sarcasm detected")   

[125, 213, 29, 47, 280, 155, 128, 47, 280, 486, 13, 247, 280, 342]
Epoch 1/25
1563/1563 [==============================] - 18s 10ms/step - loss: 0.6568 - accuracy: 0.6264
Epoch 2/25
1563/1563 [==============================] - 15s 10ms/step - loss: 0.6410 - accuracy: 0.6488
Epoch 3/25
1563/1563 [==============================] - 16s 10ms/step - loss: 0.6351 - accuracy: 0.6550
Epoch 4/25
1563/1563 [==============================] - 15s 10ms/step - loss: 0.6307 - accuracy: 0.6587
Epoch 5/25
1563/1563 [==============================] - 16s 10ms/step - loss: 0.6309 - accuracy: 0.6589
Epoch 6/25
1563/1563 [==============================] - 16s 10ms/step - loss: 0.6263 - accuracy: 0.6608
Epoch 7/25
1563/1563 [==============================] - 17s 11ms/step - loss: 0.6237 - accuracy: 0.6619
Epoch 8/25
1563/1563 [==============================] - 16s 10ms/step - loss: 0.6211 - accuracy: 0.6641
Epoch 9/25
1563/1563 [==============================] - 15s 10ms/step - loss: 0.6223 - accuracy: 0.66